OrdererOrgs:
  - Name: Orderer
    Domain: ascdpub.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Maluser1
    Domain: maluser1.ascdpub.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Maluser2
    Domain: maluser2.ascdpub.com
    Template:
      Count: 2
    Users:
      Count: 1